### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by cjshmyr** [cjshmyr/raclassic#1]
Can be broken up if work's done in smaller chunks:

Factions
- [x] Allies and Soviet
- [ ] Countries

Tech tree
- [x] Lazily restore original tech tree (expansion units still showing up, and so are ants)
- [ ] Fully restore original tech tree (fix above)
- [ ] Tech levels

Game
- [ ] Match original game speed values
- [ ] AI (original RA AI is awful, tweak hacky AI for now)

Structures
- [ ] Building bibs
- [ ] Build adjacency rules
- [ ] Implement build radius as a custom option (off by default)
- [ ] Adjust costs
- [ ] Adjust vision
- [ ] Adjust build production acceleration rate

Air units
- [ ] Adjust cost, build time, speed, vision
- [ ] Adjust movement speed, rate of turn, turret rate

Weapons
- [ ] Adjust weapon damage, range

**Comment by MustaphaTR** [comment]
Do we wanna change default value of FoW to off?

**Comment by cjshmyr** [comment]
My vote would be off but can be swayed, what do you guys think?

Definitely leave the setting there though regardless.

**Comment by FrameLimiter** [comment]
With aircraft having no vision they'd be flying around blind under the fog. So unless we give the aircraft some vision, I think this needs to be turned off by default.

**Comment by MustaphaTR** [comment]
I wanna ask some other things about removing things original didn't have:

* Building death animations.
* Cash texts on refinery and crates.
* Losing prerequisite when losing provider. (In original, for example once you get V2 by getting radar, you can still build V2s after losing the radar dome).

**Comment by cjshmyr** [comment]
1&2: Fine with being removed.
3: Can this be treated as a quality of life improvement?
4: Not a huge fan of keeping the original's behavior on this one. I think there's a few features we should treat/note as QOL improvements.

**Comment by FrameLimiter** [comment]
Anyone recall how RevealOnFire was setup? I know for sure the defense structures & long range units had it, but can't seem to recall seeing it on infantry or tanks.

**Comment by cjshmyr** [comment]
@FrameLimiter @MustaphaTR moving this to the OpenRA organization.

**Comment by MustaphaTR** [comment]
> Anyone recall how RevealOnFire was setup? I know for sure the defense structures & long range units had it, but can't seem to recall seeing it on infantry or tanks.

I gave some units 1000 range with ini editing, all seems like reveal the shroud normally. Revealed shroud don't grow back, not sure what is the case in OpenRA, tryed to test by opening 2 instances, but computer is too bad to handle it. I'm not sure what to do with fog for that.

**Comment by FrameLimiter** [comment]
Some things I'm unclear on translating from the Rules.ini to OpenRA:
∙Projectile speeds
∙Unit speeds
∙Splash radiuses (Rules.ini uses 0, 1, 3, 6, 8 for their warheads)
->Medic/Mechanic Organic/Mechanical warhead says "0" splash. Would this indicate using a splash of 0c32 since the fallout is 4x -- equaling 0c128 [infantry hitshape size]?
->OpenRA uses 0c128 splash for rifles/tanks ect. with Rules.ini using a splash of "3".
->Artillery via rules.ini says splash of 6; does this suggest a splash of 0c256?

**Comment by MustaphaTR** [comment]
Do we wanna keep the way it currently is or change the unit tooltips so it uses generic name (Enemy Structure/Vehicle/Soldier) and remove OwnerRow?

**Comment by GraionDilach** [comment]
I think you can do the permanent prereqs thingy with d2k-akin upgrades defined as freeactor for provioding them on the respectable tech buildings.

**Comment by GraionDilach** [comment]
Building survivors when they're destroyed are missing from the initial list.

**Comment by MustaphaTR** [comment]
I already have a EmitInfantryOnDeath trait for my General's Alpha mod. It is mostly a copy paste from EmitInfantryOnSell and i don't really like it, it is not really like original.

**Comment by Mailaender** [comment]
Some history: there was a dormant fork at https://github.com/Iran/ClassicRA and https://github.com/OpenRA/OpenRA/pull/2633 for our early attempts to integrate it. Maybe you can learn from our failure or even re-use some stuff.

**Comment by cjshmyr** [comment]
Been out of commission for a few weeks, sorry folks.

@FrameLimiter - We might have to use approximations in some cases, if so we could store rules.ini -> yaml conversion values on a wiki page.
@MustaphaTR - I prefer the newer tooltips for multiplayer reasons, but could go either way.
@GraionDilach - Added to list.

**Comment by cjshmyr** [comment]
pchote has work down the pipeline that lets us support more lobby options, such as an `Aftermath Units` checkbox (e.g. [ra mod's "Kill Bounties" PR](https://github.com/OpenRA/OpenRA/pull/14363/)).

Right now we're using the aftrmath.ini values for units but we are not enabling aftermath units. Perhaps we should enable these units by default right now, then bring in the checkbox after.

**Comment by MustaphaTR** [comment]
Looks like Machine Gun weapons weren't blocked in original. Do we wanna change that behaviour, as it doesn't really make much sense.

**Comment by cjshmyr** [comment]
Yeah sounds good changing that if it doesn't make sense, pretty minor.

**Comment by MustaphaTR** [comment]
> Hidden units as a lobby option (off by default)

What exactly are the hidden units? Volkov, chitzkoi, phase transport, helicarrier, ants?

**Comment by MustaphaTR** [comment]
What do we wanna do with Aircraft Husks here. They are nice visually, but as original planes died in midair, they didn't deal any crash damage, while they do here.

**Comment by FrameLimiter** [comment]
We could maybe just add a conditional death explosion to the aircraft so when we do "leave husks as a lobby option" we can toggle between the two behaviors.
e.g.
Unit Husks [x]:  Aircraft shows an explosion when dying and has no husk (original)
Unit Husks [√]: Aircraft shows no explosion when dying but spawns a husk. (current)

**Comment by cjshmyr** [comment]
I pictured hidden units as those with build icons but not actually buildable (phase transport/helicarrier), but could expand that to what you've listed?

That husk idea sounds possible once we pull the engine upgrade in.

**Comment by GraionDilach** [comment]
Another option is to remove the damagewarhead from the aircraft husk, leaving it in as a mere cosmetic change.

**Comment by cjshmyr** [comment]
Hey guys, been a while but I won't be able to dedicate time to work on raclassic. @MustaphaTR  / @FrameLimiter / others, if you guys want to change the mod's direction, todo list, or merge stuff feel free.
